export const backgroundColors = {
    white: '#ffffff',
    red: '#ffcdd2',
    pink: '#f8bbd0',
    purple: '#e1bee7',
    deepPurple: '#d1c4e9',
    indigo: '#c5cae9',
    blue: '#bbdefb',
    lightBlue: '#b3e5fc',
    cyan: '#b2ebf2',
    teal: '#b2dfdb',
    green: '#c8e6c9',
    lightGreen: '#dcedc8',
    lime: '#f0f4c3',
    yellow: '#fff9c4',
    amber: '#ffecb3',
    orange: '#ffe0b2',
    deepOrange: '#ffccbc',
    brown: '#d7ccc8',
    grey:  '#f5f5f5',
    blueGrey: '#cfd8dc'
}

export const backgroundColorsForSelect = [
    { name: 'White', id: '#ffffff' },
    { name: 'Red', id: '#ffcdd2' },
    { name: 'Pink', id: '#f8bbd0' },
    { name: 'Purple', id: '#e1bee7' },
    { name: 'Deep purple', id: '#d1c4e9' },
    { name: 'Indigo', id: '#c5cae9' },
    { name: 'Blue', id: '#bbdefb' },
    { name: 'Light blue', id: '#b3e5fc' },
    { name: 'Cyan', id: '#b2ebf2' },
    { name: 'Teal', id: '#b2dfdb' },
    { name: 'Green ', id: '#c8e6c9' },
    { name: 'Light green', id: '#dcedc8' },
    { name: 'Lime', id: '#f0f4c3' },
    { name: 'Yellow', id: '#fff9c4' },
    { name: 'Amber', id: '#ffecb3' },
    { name: 'Orange', id: '#ffe0b2' },
    { name: 'Deep orange', id: '#ffccbc' },
    { name: 'Brown', id: '#d7ccc8' },
    { name: 'Gray', id: '#f5f5f5' },
    { name: 'Blue gray', id: '#cfd8dc' }
]